### ISSUE TITLE
Move popups to a component

### ISSUE THREAD

**Issue by WeeJeWel** [printhom/devkit-core#24]
A popup should be a component as well. `./app/components/popups/`.

Open: `popup.open('id', w, h)`
Close: `popup.close('id')`

This gives the user control over settings. Also remove the embedded auth popup.

**Comment by ChrisTerBeke** [comment]
Done. implemented as service $popup with open('id', $scope) and close() functions. Close closes the active popup, since only 1 will be open at the same time. open allows you to pass the current scope (or any other scope) as second parameter. width and height should be declared in your css like any other module does.
